Repository kat-kan/kawqa-gad-playwright, pull requests merged in 2024-02, with the labels that each got.

#50 [ISSUE#48] add https status code enum
  .husky/pre-commit
  src/api/enums/api-status-code.enum.ts
Labels: enhancement

#56 [ISSUE#17] Contributing guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation

#57 [ISSUE#20] GET articles/ - add test
  tests/api/articles-endpoint-get.spec.ts
Labels: tests

#74 (tests) : fix broken POST tests after upgrading GAD to v2.5.3
  src/api/enums/api-status-code.enum.ts
  src/fixtures/api/auth.ts
  tests/api/articles-post.spec.ts
Labels: fix

#68 [ISSUE#67]POST comments/ - add test
  tests/api/comments-post.spec.ts
Labels: tests
